# Dependencies
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Nathan Phelps
tagline:          "The Portfolio"
description:      "Hacking through the day. Coding my way."
url:              https://www.somehowicode.com
baseurl:          /

author:
  name:           'Nathan Phelps'
  url:            https://twitter.com/mcphelpsius

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mcphelpsius
